apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: creative-studio
namePrefix: ""
nameSuffix: ""

commonLabels:
  app.kubernetes.io/part-of: creative-studio
  environment: dev

helmCharts:
  - name: creative-studio
    releaseName: creative-studio
    namespace: creative-studio
    version: 1.0.0
    valuesFile: ../../../helm/creative-studio/values-dev.yaml
    valuesInline: {}
    includeCRDs: false
    skipTests: true
    # Path is relative to this kustomization file.
    chartHome: ../../../helm

patches:
  - path: patches/namespace.yaml
    target:
      kind: Namespace
      name: creative-studio

resources:
  - namespace.yaml
