{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cs.backend.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cs.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStoreRefName }}
  target:
    name: {{ include "cs.backend.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "cs.labels" . | nindent 10 }}
  data:
  {{- range $key, $smName := .Values.externalSecrets.data }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ $smName | quote }}
  {{- end }}
{{- end }}
