{{- if and .Values.ingress.enabled .Values.ingress.frontendConfig.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "cs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cs.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.frontendConfig.redirectToHttps }}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  {{- end }}
  {{- with .Values.ingress.frontendConfig.sslPolicy }}
  sslPolicy: {{ . | quote }}
  {{- end }}
{{- end }}
