{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cs.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cs.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "cs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
---
{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cs.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cs.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "cs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
