{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cs.backend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cs.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.backend.serviceAccount.googleServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ . | quote }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
