apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: creative-studio

commonLabels:
  app.kubernetes.io/part-of: creative-studio
  environment: qat

helmCharts:
  - name: creative-studio
    releaseName: creative-studio
    namespace: creative-studio
    version: 1.0.0
    valuesFile: ../../../helm/creative-studio/values-qat.yaml
    includeCRDs: false
    skipTests: true
    chartHome: ../../../helm

resources:
  - namespace.yaml
